### ISSUE TITLE
Tabs on right side setting not honored at startup

### ISSUE THREAD

**Issue by gee4vee** [amblard/resizable-vertical-tabs#1]
Every time I quit and reopen Atom, the tabs are on the left side even though the check box is checked to place them on the right. I have to uncheck it and recheck it to move them to the right.

**Comment by amblard** [comment]
Thanks for reporting this issue, I will deliver a fix soon.

**Comment by amblard** [comment]
I have released a new version containing the fix. Now you should have the tabs on the right at each launch.
